### ISSUE TITLE
CustomView：UIStackViewの使用について

### ISSUE THREAD

**Issue by rujiie** [YuukiHirama/Task2#2]
この課題ではviewのframeで位置を決めるのが目的なので
UIStackViewを使わない方法で実装をお願いします。

※titleLabelなどはCustomViewとUIStackView(commonView)にaddしていますが
viewを複数のviewに子として追加することはありません。
これはiOSに限らないと思います。

**Comment by YuukiHirama** [comment]
UIStackViewを使用せずframeを使用しました。
d7abbe5

**Comment by rujiie** [comment]
確認しました。
