### ISSUE TITLE
lazyは使わないように

### ISSUE THREAD

**Issue by matsumoto777** [YuukiHirama/Task2#3]
lazyは使い所が非常に難しいので使用しないでください。
実際にいつどこで呼ばれるのか非常にあやふやになってしまうため、問題が発生したときに苦労します。

問題ないケースもあるが、明確に線を引くのが難しいので一律使用禁止。

**Comment by YuukiHirama** [comment]
lazyを使用にないように修正しました。　
0a0d90c
