### ISSUE TITLE
CustomViewのcommonInitについて

### ISSUE THREAD

**Issue by matsumoto777** [YuukiHirama/Task2#5]
CustomViewについて、
commonInitを外から呼ばないと正常に動作しないというのが問題です。
呼ばなくても動作するようにしたいです。

ViewControllerにviewDidLoadがあるように
内部でcommonInitを実行する手段があると思います。

それを探してみてもらえますか。

**Comment by YuukiHirama** [comment]
初期化にイニシャライザを実装しました。
7b27dc3

**Comment by matsumoto777** [comment]
OKです
